### ISSUE TITLE
Adaway not blocking - trying to open hosts file from app not working

### ISSUE THREAD

**Issue by Avrution** [AdAway/AdAway#2528]
I've been having this issue for a few months since moving to a new phone (Oneplus 7T, running custom rom).  Adaway doesn't seem to be blocking anything - ads still show, yet within the app it shows the webserver running and it passes the test.

I started out with the older 4.x version and in that I was unable to open the hosts file, yet it could be opened directly by navigating there in the file manager.

In 5.x when clicking on open hosts it will just return to the main adaway menu or the app will crash.

I have 4 other devices and adaway works flawlessly, never had an issue.

Tried magisk 20.4 and 21.4 - systemless module, no systemless module.  Out of ideas to try.

I see the verbose logging option and thought that might help, but can't see where to actually read the logs.  

When I run dns logging and go to a certain site that bombards with ads (searchdome.com) nothing is being blocked, yet in the dns request menu I see almost everything has the red circle with the line through it (blocking?).

Help?  Advice?

**Comment by Dinjoralo** [comment]
I was having these problems too. I believe I fixed it by hitting the "disable ad blocking" button in Adaway, using a root browser to delete the hosts file and symlink, disabling the systemless hosts module, uninstalling AdAway, restarting my phone, then reinstalling AdAway and re enabling it. This might not be quite right, I tried a lot of things, but I know disabling systemless hosts was an important part.

**Comment by Avrution** [comment]
Thanks I will try those.  Any idea where the symlink is located?

**Comment by Dinjoralo** [comment]
On my oneplus 6t, the symlink was in etc\ while the proper hosts file was in data\data.

**Comment by Avrution** [comment]
Still no real luck. It is odd. Running the DNS filter shows everything should be blocked, but ads still show up.

**Comment by Andik23** [comment]
I have the exact same problem, did you solve it?
Everything looks good, Adaway reports success and prompts you to restart. But then no ads will be blocked.

I have a Galaxy S21, Android 11, AUC8.

**Comment by Avrution** [comment]
For the moment I think it might be working.  I redid everything about 3 times before I could even open the host file correctly

**Comment by dr-kaisar** [comment]
Could you find any solution? I am also facing this issue.

**Comment by Avrution** [comment]
As mentioned above, I just had to keep trying it over and over.  The only way I knew it actually worked is because my amazon app stopped working since it was being blocked

**Comment by killerlearner** [comment]
Ig Google implement new ad system something like that. I am using mine old device in which adaway was working perfectly but nowadays it didn't blocking ad and ad keep popping up and yup I am using rooted device.
